language: node_js
node_js:
  - '8'
  - '10'

# cache:
#   directories:
#     - node_modules

before_install:
  - export TZ='Asia/Beijing' # 更改时区

install:
  - npm install

script:
  # 为了能在git-pages预览 单独发布带有二级域名的包
  - npm run build:git
  # 默认(大部分)
  # - npm run build

after_script:
  - cd ./dist
  - git init 
  - git config user.name "BiYuqi"
  - git config user.email "biyuqiwan@163.com"
  - git add .
  - git commit -m "Travis CI Auto Builder at `date +"%Y-%m-%d %H:%M"`"
  - git push --force --quiet "https://${WEBPACK_SEED}@${GH_REF}" master:gh-pages

branches:
  only:
    - master
env:
 global:
   - GH_REF: github.com/BiYuqi/webpack-seed.git